/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [SaleLineId]
      ,[SaleId]
      ,[ProductId]
      ,[ProductCode]
      ,[ProductName]
      ,[ProductVariantId]
      ,[VariantCode]
      ,[VariantName]
      ,[ProviderProductId]
      ,[Quantity]
      ,[SettledQty]
      ,[PaidQty]
      ,[BasePriceType]
      ,[BasePrice]
      ,[SalePrice]
      ,[IsSalePriceEdited]
      ,[PriceFinalizedAt]
      ,[PriceFinalizedByUserId]
      ,[ProductBaseCommissionId]
      ,[CommissionType]
      ,[CommissionValue]
      ,[CalculatedAgentCommission]
      ,[FinalAgentCommission]
      ,[SuperCRMCommissionEarned]
      ,[IsCommissionFinalized]
      ,[CreatedAt]
      ,[UpdatedAt]
      ,[UpdatedByUserId]
      ,[SalesUnitId]
      ,[SalesUnitCode]
      ,[LineTotalAmount]
      ,[MonthlyInstallmentAmount]
      ,[NoOfInstallment]
      ,[FirstInstallmentDate]
      ,[Completed]
      ,[CompletedDate]
      ,[CancelledOrRejected]
      ,[CancelledOrRejectedDate]
      ,[SpecialNotes]
      ,[Remarks]
  FROM [db_acb300_supercrmuk].[dbo].[SaleLines]
  where SaleId IN ('998127C3-15DE-44CD-8DB4-5D32DD223832','22EBCD86-7821-4E97-99FB-B49686D4C892')

  --UPDATE
  --[db_acb300_supercrmuk].[dbo].[SaleLines]
  --SET CommissionValue = 3000, CalculatedAgentCommission = 3000
  --where SaleId IN ('998127C3-15DE-44CD-8DB4-5D32DD223832','22EBCD86-7821-4E97-99FB-B49686D4C892')