/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [SaleId]
      ,[CustomerId]
	  ,[AgentCommissionAmount]
      ,[CustomerBusinessId]
      ,[ProviderId]
      ,[OrderSourceType]
      ,[SaleChannelType]
      ,[SoldByUserId]
      ,[SoldByAgentId]
      ,[SoldByAgentCode]
      ,[IsCommissionApplicable]
      ,[OrderDate]
      ,[OrderStatus]
      ,[ProviderCommissionEarned]
      
      ,[IsProviderCommissionReceived]
      ,[IsAgentCommissionDistributed]
      ,[CreatedByUserId]
      ,[CreatedAt]
      ,[UpdatedAt]
      ,[UpdatedByUserId]
      ,[OrderNo]
      ,[SalesOrderStatus]
      ,[SentToProviderDate]
      ,[SentToProviderUserId]
      ,[ProviderAcceptedDate]
      ,[ProviderAcceptedUserId]
      ,[ProviderRejectedDate]
      ,[ProviderRejectedUserId]
      ,[DeliveredDate]
      ,[DeliveredDateUpdatedBy]
      ,[CancelledDate]
      ,[CancelledReason]
      ,[CancelledByUserId]
      ,[OnHoldDate]
      ,[OnHoldReason]
      ,[OnHoldByUserId]
      ,[SpecialNotes]
      ,[EmailSentToCustomer]
      ,[EmailSentToProvider]
      ,[CompletedDate]
      ,[ServiceStartDate]
      ,[NextRenewDate]
      ,[NoOfRenew]
      ,[RenewNotes]
      ,[ManagerUserId]
  FROM [db_acb300_supercrmuk].[dbo].[Sales]
  where OrderNo IN ('SO-2608-6032' , 'SO-2608-2146')


  UPDATE [db_acb300_supercrmuk].[dbo].[Sales]
  SET AgentCommissionAmount = 3000
  where OrderNo IN ('SO-2608-6032' , 'SO-2608-2146')
